package javaimpls.two.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Order")
public class Order {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String orderId;

    @DynamoDBAttribute String market;
    @DynamoDBAttribute String entitySymbol;
    @DynamoDBAttribute String entityName;
    @DynamoDBAttribute String orderType;
    @DynamoDBAttribute Integer shares;
    @DynamoDBAttribute Float price;
}
